name: GitHub Actions for java project
on: [workflow_dispatch]
jobs:
  CI_JOB: 
    runs-on: ubuntu-latest
    steps: 
    
    - name: Code Checkout 
      uses: actions/checkout@v4

    - name: Set up java 
      uses: ./.github/actions/set-up-java
      with:
        java-version: "11"

    - name: Build the project
      run: mvn clean package 

    - name: list
      run: ls -l target
         

                  
         