name: GitHub Actions for java project
on: [workflow_dispatch]
jobs:
  CI_JOB: 
    runs-on: ubuntu-latest
    steps: 
    
    - name: Code Checkout 
      uses: actions/checkout@v4

    - name: Set up java 
      uses: ./.github/actions/setup-java
      with:
        java-version: "11"

    - name: sonar-scanner 
      run: |  
        java -version 
        mvn -v    

    - name: sonar-scanner 
      run: /opt/sonar-scanner-4.8.1.3023-linux/bin/sonar-scanner --version

    # - name: sonar push
    #   run: /opt/sonar-scanner-4.8.1.3023-linux/bin/sonar-scanner -Dsonar.host.url=http://18.208.246.59:9000 -Dsonar.login=admin -Dsonar.password=admin123 -Dsonar.projectKey=javaProject  

    # - name: Build the project
    #   run: mvn clean package 

    # - name: list
    #   run: ls -l target
         

                  
         